// packages/solid/src/useAskable.ts
import { createSignal, createEffect, createMemo, onCleanup } from 'solid-js';
import { createAskableContext } from '@askable-ui/core';
import type { AskableEvent, AskableFocus, AskableContext } from '@askable-ui/core';

let globalCtx: AskableContext | null = null;
let refCount = 0;

function getGlobalCtx(): AskableContext {
  if (!globalCtx) {
    globalCtx = createAskableContext();
  }
  return globalCtx;
}

export interface UseAskableResult {
  /** Reactive accessor — call as focus() in JSX or reactive contexts */
  focus: () => AskableFocus | null;
  /** Reactive accessor — derived from focus, updates when focus changes */
  promptContext: () => string;
  ctx: AskableContext;
}

export function useAskable(options?: {
  events?: AskableEvent[];
  ctx?: AskableContext;
}): UseAskableResult {
  const usesProvidedCtx = Boolean(options?.ctx);
  const ctx = options?.ctx ?? getGlobalCtx();

  const [focus, setFocus] = createSignal<AskableFocus | null>(ctx.getFocus());

  const promptContext = createMemo(() => {
    focus(); // track the signal so memo updates when focus changes
    return ctx.toPromptContext();
  });

  createEffect(() => {
    if (!usesProvidedCtx) {
      refCount++;
      if (typeof document !== 'undefined') {
        ctx.observe(document, { events: options?.events });
      }
    }

    const handler = (f: AskableFocus) => setFocus(() => f);
    const clearHandler = (_: null) => setFocus(null);
    ctx.on('focus', handler);
    ctx.on('clear', clearHandler);

    onCleanup(() => {
      ctx.off('focus', handler);
      ctx.off('clear', clearHandler);
      if (!usesProvidedCtx) {
        refCount--;
        if (refCount === 0) {
          globalCtx?.destroy();
          globalCtx = null;
        }
      }
    });
  });

  return { focus, promptContext, ctx };
}

// packages/react-native/src/useAskable.ts
import { useEffect, useState } from 'react';
import { createAskableContext } from '@askable-ui/core';
import type { AskableContext, AskableContextOptions, AskableFocus } from '@askable-ui/core';

export interface UseAskableOptions extends AskableContextOptions {
  /** Provide an existing context instead of creating a new one. */
  ctx?: AskableContext;
}

export interface UseAskableResult {
  focus: AskableFocus | null;
  promptContext: string;
  ctx: AskableContext;
}

export function useAskable(options?: UseAskableOptions): UseAskableResult {
  const [ctx] = useState<AskableContext>(() => options?.ctx ?? createAskableContext(options));
  const [focus, setFocus] = useState<AskableFocus | null>(() => ctx.getFocus());

  useEffect(() => {
    const handleFocus = (nextFocus: AskableFocus) => setFocus(nextFocus);
    const handleClear = (_: null) => setFocus(null);

    ctx.on('focus', handleFocus);
    ctx.on('clear', handleClear);

    return () => {
      ctx.off('focus', handleFocus);
      ctx.off('clear', handleClear);
      if (!options?.ctx) {
        ctx.destroy();
      }
    };
  }, [ctx, options?.ctx]);

  return {
    focus,
    promptContext: ctx.toPromptContext(),
    ctx,
  };
}
