// packages/solid/src/useAskableDialogSource.ts
import { createEffect, createSignal, onCleanup } from 'solid-js';
import { createAskableDialogSource, createAskableDialogObserver, buildDialogSnapshot } from '@askable-ui/core';
import type {
  AskableCreateDialogSourceOptions,
  AskableDialogClosedEntry,
  AskableDialogEntry,
  AskableDialogKind,
  AskableDialogSourceSnapshot,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableDialogClosedEntry, AskableDialogEntry, AskableDialogKind, AskableDialogSourceSnapshot };

export interface UseAskableDialogSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateDialogSourceOptions, 'getSnapshot'> {
  /** Source registration id. Defaults to "dialogs". */
  id?: string;
  /** Overlays already open on mount, bottom of the stack first. */
  open?: AskableDialogEntry[];
  /**
   * Detect native `<dialog>`, ARIA dialogs, and popovers from the DOM instead of
   * calling `openDialog`/`closeDialog` by hand. Manual actions are ignored while
   * this is on — the DOM is the source of truth.
   */
  autoDetect?: boolean;
  /** Where auto-detection scans. Defaults to `document`. */
  root?: ParentNode | null;
}

export interface UseAskableDialogSourceResult extends UseAskableSourceResult {
  snapshot: () => AskableDialogSourceSnapshot | null;
  openDialog: (entry: AskableDialogEntry) => void;
  closeDialog: (id: string, reason?: string) => void;
  closeTopmost: (reason?: string) => void;
  setDialogs: (entries: AskableDialogEntry[]) => void;
  closeAll: (reason?: string) => void;
}

function toClosedEntry(entry: AskableDialogEntry, reason: string | null): AskableDialogClosedEntry {
  return {
    id: entry.id,
    title: entry.title ?? null,
    kind: entry.kind ?? 'dialog',
    reason,
    closedAt: new Date().toISOString(),
  };
}

/**
 * SolidJS primitive that tracks which modal, drawer, or popover is open and
 * exposes it to AI assistants so they answer about the overlay in front of the
 * user instead of the page behind it.
 *
 * @example
 * ```tsx
 * const { snapshot, openDialog, closeDialog } = useAskableDialogSource();
 * openDialog({ id: 'delete', title: 'Delete workspace', actions: ['Cancel', 'Delete'] });
 * ```
 *
 * @example
 * ```tsx
 * // Zero-config: read open overlays straight from the DOM.
 * useAskableDialogSource({ autoDetect: true });
 * ```
 */
export function useAskableDialogSource(
  options: UseAskableDialogSourceOptions = {},
): UseAskableDialogSourceResult {
  const { id = 'dialogs', open: initialOpen = [], autoDetect = false, root, describe, kind, enabled, ctx, name, events } = options;

  const [snapshot, setSnapshot] = createSignal<AskableDialogSourceSnapshot | null>(
    buildDialogSnapshot(initialOpen, null, initialOpen.length > 0 ? new Date().toISOString() : null),
  );

  const source = createAskableDialogSource({ describe, kind, getSnapshot: snapshot });
  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  function updateSnapshot(updater: (prev: AskableDialogSourceSnapshot) => AskableDialogSourceSnapshot): void {
    setSnapshot((prev) => (prev ? updater(prev) : prev));
    result.notifyChanged();
  }

  function setDialogs(entries: AskableDialogEntry[]): void {
    updateSnapshot((prev) => buildDialogSnapshot(entries, prev.lastClosed, new Date().toISOString()));
  }

  function openDialog(entry: AskableDialogEntry): void {
    updateSnapshot((prev) => {
      const openedAt = entry.openedAt ?? new Date().toISOString();
      const existing = prev.open.findIndex((item) => item.id === entry.id);
      const next = existing >= 0
        ? prev.open.map((item, index) => (index === existing ? { ...entry, openedAt: item.openedAt ?? openedAt } : item))
        : [...prev.open, { ...entry, openedAt }];
      return buildDialogSnapshot(next, prev.lastClosed, openedAt);
    });
  }

  function closeDialog(dialogId: string, reason?: string): void {
    updateSnapshot((prev) => {
      const closing = prev.open.find((item) => item.id === dialogId);
      if (!closing) return prev;
      const next = prev.open.filter((item) => item.id !== dialogId);
      return buildDialogSnapshot(next, toClosedEntry(closing, reason ?? null), new Date().toISOString());
    });
  }

  function closeTopmost(reason?: string): void {
    updateSnapshot((prev) => {
      if (prev.open.length === 0) return prev;
      const closing = prev.open[prev.open.length - 1]!;
      return buildDialogSnapshot(prev.open.slice(0, -1), toClosedEntry(closing, reason ?? null), new Date().toISOString());
    });
  }

  function closeAll(reason?: string): void {
    updateSnapshot((prev) => {
      if (prev.open.length === 0) return prev;
      const closing = prev.open[prev.open.length - 1]!;
      return buildDialogSnapshot([], toClosedEntry(closing, reason ?? null), new Date().toISOString());
    });
  }

  createEffect(() => {
    if (!autoDetect) return;
    const observer = createAskableDialogObserver({ root, onChange: setDialogs });
    onCleanup(() => observer.stop());
  });

  return { ...result, snapshot, openDialog, closeDialog, closeTopmost, setDialogs, closeAll };
}

// packages/qwik/src/useAskableDialogSource.ts
import { $, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import type { QRL, SyncQRL } from '@builder.io/qwik';
import { createAskableDialogSource, createAskableDialogObserver, buildDialogSnapshot } from '@askable-ui/core';
import type {
  AskableCreateDialogSourceOptions,
  AskableDialogClosedEntry,
  AskableDialogEntry,
  AskableDialogKind,
  AskableDialogSourceSnapshot,
} from '@askable-ui/core';
import {
  useAskableSource,
  type UseAskableSourceOptions,
  type UseAskableSourceResult,
} from './useAskableSource.js';

export type { AskableDialogClosedEntry, AskableDialogEntry, AskableDialogKind, AskableDialogSourceSnapshot };

export interface UseAskableDialogSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateDialogSourceOptions, 'describe' | 'getSnapshot'> {
  id?: string;
  /** Overlays already open on mount, bottom of the stack first. */
  open?: AskableDialogEntry[];
  /**
   * Detect native `<dialog>`, ARIA dialogs, and popovers from the DOM instead of
   * calling `openDialog`/`closeDialog` by hand. Manual actions are ignored while
   * this is on — the DOM is the source of truth.
   */
  autoDetect?: boolean;
  /** Resume-safe synchronous source description callback. */
  describe?: SyncQRL<NonNullable<AskableCreateDialogSourceOptions['describe']>>;
}

export interface UseAskableDialogSourceResult extends UseAskableSourceResult {
  snapshot: ReturnType<typeof useSignal<AskableDialogSourceSnapshot | null>>;
  openDialog: QRL<(entry: AskableDialogEntry) => Promise<void>>;
  closeDialog: QRL<(id: string, reason?: string) => Promise<void>>;
  closeTopmost: QRL<(reason?: string) => Promise<void>>;
  setDialogs: QRL<(entries: AskableDialogEntry[]) => Promise<void>>;
  closeAll: QRL<(reason?: string) => Promise<void>>;
}

function toClosedEntry(entry: AskableDialogEntry, reason: string | null): AskableDialogClosedEntry {
  return {
    id: entry.id,
    title: entry.title ?? null,
    kind: entry.kind ?? 'dialog',
    reason,
    closedAt: new Date().toISOString(),
  };
}

/** Qwik hook that tracks the open dialog/overlay stack and exposes resumable actions. */
export function useAskableDialogSource(
  options: UseAskableDialogSourceOptions = {},
): UseAskableDialogSourceResult {
  const {
    id = 'dialogs',
    open: initialOpen = [],
    autoDetect = false,
    describe,
    kind,
    enabled,
    ctx,
    ctx$,
    name,
    events,
    viewport,
    textExtractor,
    sanitizeMeta,
    sanitizeText,
    sanitizeSource,
    maxHistory,
  } = options;

  const snapshot = useSignal<AskableDialogSourceSnapshot | null>(
    buildDialogSnapshot(initialOpen, null, initialOpen.length > 0 ? new Date().toISOString() : null),
  );
  const sourceFactory = $(async () => createAskableDialogSource({
    describe: await describe?.resolve(),
    kind,
    getSnapshot: () => snapshot.value,
  }));
  const result = useAskableSource(id, sourceFactory, {
    enabled, ctx, ctx$, name, events, viewport, textExtractor,
    sanitizeMeta, sanitizeText, sanitizeSource, maxHistory,
  });
  const notifyChanged = result.notifyChanged;

  const setDialogs = $(async (entries: AskableDialogEntry[]): Promise<void> => {
    const previous = snapshot.value;
    if (!previous) return;
    snapshot.value = buildDialogSnapshot(entries, previous.lastClosed, new Date().toISOString());
    await notifyChanged();
  });

  const openDialog = $(async (entry: AskableDialogEntry): Promise<void> => {
    const previous = snapshot.value;
    if (!previous) return;
    const openedAt = entry.openedAt ?? new Date().toISOString();
    const index = previous.open.findIndex((current) => current.id === entry.id);
    const open = index >= 0
      ? previous.open.map((current, currentIndex) =>
          currentIndex === index ? { ...entry, openedAt: current.openedAt ?? openedAt } : current)
      : [...previous.open, { ...entry, openedAt }];
    snapshot.value = buildDialogSnapshot(open, previous.lastClosed, openedAt);
    await notifyChanged();
  });

  const closeDialog = $(async (dialogId: string, reason?: string): Promise<void> => {
    const previous = snapshot.value;
    if (!previous) return;
    const closing = previous.open.find((current) => current.id === dialogId);
    if (!closing) return;
    snapshot.value = buildDialogSnapshot(
      previous.open.filter((current) => current.id !== dialogId),
      toClosedEntry(closing, reason ?? null),
      new Date().toISOString(),
    );
    await notifyChanged();
  });

  const closeTopmost = $(async (reason?: string): Promise<void> => {
    const previous = snapshot.value;
    if (!previous || previous.open.length === 0) return;
    const closing = previous.open[previous.open.length - 1]!;
    snapshot.value = buildDialogSnapshot(
      previous.open.slice(0, -1),
      toClosedEntry(closing, reason ?? null),
      new Date().toISOString(),
    );
    await notifyChanged();
  });

  const closeAll = $(async (reason?: string): Promise<void> => {
    const previous = snapshot.value;
    if (!previous || previous.open.length === 0) return;
    const closing = previous.open[previous.open.length - 1]!;
    snapshot.value = buildDialogSnapshot([], toClosedEntry(closing, reason ?? null), new Date().toISOString());
    await notifyChanged();
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    if (!autoDetect) return;
    const observer = createAskableDialogObserver({ onChange: (entries) => void setDialogs(entries) });
    cleanup(() => observer.stop());
  });

  return Object.assign(result, {
    snapshot,
    openDialog,
    closeDialog,
    closeTopmost,
    setDialogs,
    closeAll,
  });
}
